config/routes.rb
Rails.application.routes.draw do
  resources :pres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pre.rb
class Pre < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pres_controller.rb
class PresController < ApplicationController
  before_action :set_pre, only: [:show, :edit, :update, :destroy]

  # GET /pres
  # GET /pres.json
  def index
    @pres = Pre.all
  end

  # GET /pres/1
  # GET /pres/1.json
  def show
  end

  # GET /pres/new
  def new
    @pre = Pre.new
  end

  # GET /pres/1/edit
  def edit
  end

  # POST /pres
  # POST /pres.json
  def create
    @pre = Pre.new(pre_params)

    respond_to do |format|
      if @pre.save
        format.html { redirect_to @pre, notice: 'Pre was successfully created.' }
        format.json { render :show, status: :created, location: @pre }
      else
        format.html { render :new }
        format.json { render json: @pre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pres/1
  # PATCH/PUT /pres/1.json
  def update
    respond_to do |format|
      if @pre.update(pre_params)
        format.html { redirect_to @pre, notice: 'Pre was successfully updated.' }
        format.json { render :show, status: :ok, location: @pre }
      else
        format.html { render :edit }
        format.json { render json: @pre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pres/1
  # DELETE /pres/1.json
  def destroy
    @pre.destroy
    respond_to do |format|
      format.html { redirect_to pres_url, notice: 'Pre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pre
      @pre = Pre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pre_params
      params.require(:pre).permit(:nombre, :correo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pres_helper.rb
module PresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pres/_form.html.erb
<%= form_with(model: pre, local: true) do |form| %>
  <% if pre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pre.errors.count, "error") %> prohibited this pre from being saved:</h2>

      <ul>
      <% pre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pres/edit.html.erb
<h1>Editing Pre</h1>

<%= render 'form', pre: @pre %>

<%= link_to 'Show', @pre %> |
<%= link_to 'Back', pres_path %>

app/views/pres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pres</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pres.each do |pre| %>
      <tr>
        <td><%= pre.nombre %></td>
        <td><%= pre.correo %></td>
        <td><%= link_to 'Show', pre %></td>
        <td><%= link_to 'Edit', edit_pre_path(pre) %></td>
        <td><%= link_to 'Destroy', pre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pre', new_pre_path %>

app/views/pres/new.html.erb
<h1>New Pre</h1>

<%= render 'form', pre: @pre %>

<%= link_to 'Back', pres_path %>

app/views/pres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @pre.nombre %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @pre.correo %>
</p>

<%= link_to 'Edit', edit_pre_path(@pre) %> |
<%= link_to 'Back', pres_path %>